In [2]:
import pandas as pd 
import numpy as np 

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
state_data_df = pd.read_csv('NFCS_2021_State_Data_220627.csv')
state_data_df

,NFCSID,STATEQ,CENSUSDIV,CENSUSREG,A50A,A3Ar_w,A50B,A4A_new_w,A5_2015,A6,...,M6,M7,M8,M31,M50,M9,M10,wgt_n2,wgt_d2,wgt_s3
0,2021010001,41,5,3,2,2,8,1,6,1,...,1,3,2,2,2,1,2,0.834316,0.539386,0.725252
1,2021010002,36,3,2,2,2,8,1,6,4,...,98,98,98,98,98,1,98,1.083618,1.075806,0.930410
2,2021010003,3,8,4,1,6,6,1,6,4,...,1,3,98,3,1,1,2,0.396368,2.123406,0.944175
3,2021010004,3,8,4,2,4,10,2,2,1,...,1,98,98,1,1,1,2,0.374328,2.372112,1.011643
4,2021010005,36,3,2,2,4,10,1,3,4,...,1,98,98,98,98,98,98,1.362034,1.159651,0.907194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27113,2021037114,13,8,4,2,1,7,1,4,2,...,1,1,98,3,98,2,98,0.395557,0.481927,0.830207
27114,2021037115,12,9,4,1,1,1,2,2,2,...,98,98,4,98,98,98,98,1.484577,0.213549,1.845119
27115,2021037116,12,9,4,1,1,1,2,6,2,...,1,3,99,2,1,1,98,1.801261,0.205415,1.394245
27116,2021037117,9,5,3,2,1,7,1,3,2,...,1,1,98,98,98,98,98,1.033049,0.087797,1.470584
27117,2021037118,12,9,4,2,1,7,2,4,2,...,1,3,2,2,3,1,2,1.920182,0.232848,1.355830

In [4]:
state_data_df.info()
state_data_df.isna()
state_data_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27118 entries, 0 to 27117
Columns: 126 entries, NFCSID to wgt_s3
dtypes: float64(3), int64(83), object(40)
memory usage: 26.1+ MB

,NFCSID,STATEQ,CENSUSDIV,CENSUSREG,A50A,A3Ar_w,A50B,A4A_new_w,A5_2015,A6,...,M6,M7,M8,M31,M50,M9,M10,wgt_n2,wgt_d2,wgt_s3
count,2.711800e+04,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,...,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000
mean,2.021024e+09,25.719301,5.339627,2.743418,1.540342,3.732650,6.974703,1.260196,4.422450,1.890921,...,15.971716,24.608599,40.859208,30.128033,33.857364,20.983738,45.376945,1.000000,1.000000,1.000000
std,7.828437e+03,14.863040,2.597738,1.057597,0.498379,1.665568,3.435199,0.438750,1.710966,1.165150,...,34.797002,40.239771,47.100468,43.284233,45.448122,39.141361,47.901479,0.664533,0.806993,0.301259
min,2.021010e+09,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.285976,0.062408,0.270807
25%,2.021017e+09,12.000000,3.000000,2.000000,1.000000,2.000000,4.000000,1.000000,3.000000,1.000000,...,1.000000,3.000000,2.000000,2.000000,1.000000,1.000000,2.000000,0.462335,0.365107,0.839477
50%,2.021024e+09,26.000000,5.000000,3.000000,2.000000,4.000000,7.000000,1.000000,4.000000,2.000000,...,1.000000,3.000000,3.000000,3.000000,2.000000,1.000000,2.000000,0.846939,0.783109,0.952120
75%,2.021030e+09,38.000000,8.000000,4.000000,2.000000,5.000000,10.000000,2.000000,6.000000,2.000000,...,2.000000,3.000000,98.000000,98.000000,98.000000,2.000000,98.000000,1.341735,1.338188,1.093767
max,2.021037e+09,51.000000,9.000000,4.000000,2.000000,6.000000,12.000000,2.000000,7.000000,5.000000,...,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,5.355691,5.395601,11.127572

In [5]:
state_data_df.corr()

,NFCSID,STATEQ,CENSUSDIV,CENSUSREG,A50A,A3Ar_w,A50B,A4A_new_w,A5_2015,A6,...,M6,M7,M8,M31,M50,M9,M10,wgt_n2,wgt_d2,wgt_s3
NFCSID,1.000000,-1.656258e-03,6.674616e-02,6.422492e-02,-0.138229,-0.033219,-0.136432,0.008718,-0.075131,-0.015274,...,-0.022884,-0.013770,0.006935,-0.018303,-0.018747,-0.030050,-0.010656,-0.024189,-1.701468e-01,4.427928e-02
STATEQ,-0.001656,1.000000e+00,-1.483520e-01,-1.506659e-01,0.005775,0.015454,0.012520,-0.137249,0.011515,-0.013069,...,-0.009786,-0.004356,0.012203,-0.006818,-0.016367,-0.022390,0.007956,0.031813,-2.435679e-01,-6.661083e-10
CENSUSDIV,0.066746,-1.483520e-01,1.000000e+00,9.691671e-01,-0.002010,-0.024450,-0.013604,0.145230,-0.009706,0.003041,...,-0.007075,-0.004950,-0.008666,-0.009122,-0.005606,0.014489,-0.007393,-0.050520,-1.500266e-09,8.156235e-10
CENSUSREG,0.064225,-1.506659e-01,9.691671e-01,1.000000e+00,-0.000511,-0.022656,-0.011430,0.143405,-0.010406,0.002425,...,-0.007373,-0.005761,-0.010947,-0.008936,-0.003856,0.011526,-0.003598,-0.088276,-1.326807e-09,7.159297e-10
A50A,-0.138229,5.775382e-03,-2.009606e-03,-5.106655e-04,1.000000,0.008507,0.874605,0.005286,-0.078976,0.123287,...,0.116050,0.167482,0.172135,0.169926,0.120615,0.071900,0.221418,-0.081969,-7.018321e-02,-1.942138e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
M9,-0.030050,-2.239036e-02,1.448910e-02,1.152561e-02,0.071900,-0.214286,-0.041310,0.111456,-0.210285,0.052503,...,0.369376,0.372102,0.229811,0.341686,0.265534,1.000000,0.342283,0.068611,5.458768e-02,5.956599e-02
M10,-0.010656,7.955776e-03,-7.392805e-03,-3.597582e-03,0.221418,-0.100904,0.143817,0.015936,-0.240305,0.082256,...,0.260000,0.341589,0.359210,0.322153,0.261569,0.342283,1.000000,0.020070,3.182124e-04,2.486282e-02
wgt_n2,-0.024189,3.181282e-02,-5.051980e-02,-8.827608e-02,-0.081969,-0.031466,-0.086609,0.382229,-0.145776,0.019492,...,0.048065,0.038548,-0.005239,0.029440,0.034946,0.068611,0.020070,1.000000,1.209898e-01,2.549456e-01
wgt_d2,-0.170147,-2.435679e-01,-1.500266e-09,-1.326807e-09,-0.070183,-0.023498,-0.072486,0.239802,-0.105558,0.003233,...,0.033190,0.026470,-0.020803,0.018642,0.021959,0.054588,0.000318,0.120990,1.000000e+00,1.615530e-01
wgt_s3,0.044279,-6.661083e-10,8.156235e-10,7.159297e-10,-0.194214,-0.032918,-0.185020,0.337994,-0.300157,0.036823,...,0.037669,0.025827,0.000171,0.021709,0.032445,0.059566,0.024863,0.254946,1.615530e-01,1.000000e+00

In [6]:
state_data_df.describe(include='all')

,NFCSID,STATEQ,CENSUSDIV,CENSUSREG,A50A,A3Ar_w,A50B,A4A_new_w,A5_2015,A6,...,M6,M7,M8,M31,M50,M9,M10,wgt_n2,wgt_d2,wgt_s3
count,2.711800e+04,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,...,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000,27118.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2.021024e+09,25.719301,5.339627,2.743418,1.540342,3.732650,6.974703,1.260196,4.422450,1.890921,...,15.971716,24.608599,40.859208,30.128033,33.857364,20.983738,45.376945,1.000000,1.000000,1.000000
std,7.828437e+03,14.863040,2.597738,1.057597,0.498379,1.665568,3.435199,0.438750,1.710966,1.165150,...,34.797002,40.239771,47.100468,43.284233,45.448122,39.141361,47.901479,0.664533,0.806993,0.301259
min,2.021010e+09,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.285976,0.062408,0.270807
25%,2.021017e+09,12.000000,3.000000,2.000000,1.000000,2.000000,4.000000,1.000000,3.000000,1.000000,...,1.000000,3.000000,2.000000,2.000000,1.000000,1.000000,2.000000,0.462335,0.365107,0.839477
50%,2.021024e+09,26.000000,5.000000,3.000000,2.000000,4.000000,7.000000,1.000000,4.000000,2.000000,...,1.000000,3.000000,3.000000,3.000000,2.000000,1.000000,2.000000,0.846939,0.783109,0.952120
75%,2.021030e+09,38.000000,8.000000,4.000000,2.000000,5.000000,10.000000,2.000000,6.000000,2.000000,...,2.000000,3.000000,98.000000,98.000000,98.000000,2.000000,98.000000,1.341735,1.338188,1.093767
max,2.021037e+09,51.000000,9.000000,4.000000,2.000000,6.000000,12.000000,2.000000,7.000000,5.000000,...,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,5.355691,5.395601,11.127572

In [7]:
state_data_df.describe(exclude='number')

,A10,A21_2015,A14,J6,J8,J9,J51_1,J51_2,J51_3,J51_4,...,F2_4,F2_5,F2_6,G33,G35,G22_2015,M21_1,M21_2_2015,M21_3,M21_4
count,27118,27118,27118,27118,27118,27118,27118,27118,27118,27118,...,27118,27118,27118,27118,27118,27118,27118,27118,27118,27118
unique,9,5,6,5,5,5,3,3,3,3,...,5,5,5,5,7,5,5,5,5,5
top,,2,,,2,,1,0,0,0,...,2,2,2,,,,,,,
freq,11388,14958,11388,17790,11491,21060,12541,14203,13174,20043,...,17320,18531,18026,20667,20667,20667,21353,22353,21353,26121