In [3]:
import pandas as pd # for working with data
import numpy as np # for working with data
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
state_data_df = pd.read_csv('./NFCS_2021_State_Data_220627.csv')
state_data_df

,NFCSID,STATEQ,CENSUSDIV,CENSUSREG,A50A,A3Ar_w,A50B,A4A_new_w,A5_2015,A6,...,M6,M7,M8,M31,M50,M9,M10,wgt_n2,wgt_d2,wgt_s3
0,2021010001,41,5,3,2,2,8,1,6,1,...,1,3,2,2,2,1,2,0.834316,0.539386,0.725252
1,2021010002,36,3,2,2,2,8,1,6,4,...,98,98,98,98,98,1,98,1.083618,1.075806,0.930410
2,2021010003,3,8,4,1,6,6,1,6,4,...,1,3,98,3,1,1,2,0.396368,2.123406,0.944175
3,2021010004,3,8,4,2,4,10,2,2,1,...,1,98,98,1,1,1,2,0.374328,2.372112,1.011643
4,2021010005,36,3,2,2,4,10,1,3,4,...,1,98,98,98,98,98,98,1.362034,1.159651,0.907194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27113,2021037114,13,8,4,2,1,7,1,4,2,...,1,1,98,3,98,2,98,0.395557,0.481927,0.830207
27114,2021037115,12,9,4,1,1,1,2,2,2,...,98,98,4,98,98,98,98,1.484577,0.213549,1.845119
27115,2021037116,12,9,4,1,1,1,2,6,2,...,1,3,99,2,1,1,98,1.801261,0.205415,1.394245
27116,2021037117,9,5,3,2,1,7,1,3,2,...,1,1,98,98,98,98,98,1.033049,0.087797,1.470584
27117,2021037118,12,9,4,2,1,7,2,4,2,...,1,3,2,2,3,1,2,1.920182,0.232848,1.355830

In [5]:
state_data_df.info()
state_data_df.isna()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27118 entries, 0 to 27117
Columns: 126 entries, NFCSID to wgt_s3
dtypes: float64(3), int64(83), object(40)
memory usage: 26.1+ MB

,NFCSID,STATEQ,CENSUSDIV,CENSUSREG,A50A,A3Ar_w,A50B,A4A_new_w,A5_2015,A6,...,M6,M7,M8,M31,M50,M9,M10,wgt_n2,wgt_d2,wgt_s3
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27113,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27114,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27115,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27116,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27117,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

Important Variables: 
M20: Was financial education offered by a school or college you attended, or a workplace where you were employed?

Dependent Variable:
J4: In a typical month, how difficult is it for you to cover your expenses and pay all your bills?

In [6]:
NCFS_DF = state_data_df[['STATEQ', 'CENSUSREG']]
NCFS_DF1 = state_data_df[[]]